### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by cn2amz** [moltin/gatsby-demo-store#13]
E:\learning\gatsby\gatsby-demo-store (master -> origin)
$ gatsby develop
success open and validate gatsby-configs — 0.009 s
success load plugins — 1.687 s
success onPreInit — 0.004 s
success initialize cache — 0.006 s
success copy gatsby files — 0.253 s
success onPreBootstrap — 0.018 s
warning The @moltin/gatsby-source-moltin plugin has generated no Gatsby nodes. Do you need it?
success source and transform nodes — 12.310 s
success building schema — 0.344 s
error gatsby-node.js returned an error

  TypeError: Cannot read property 'allProducts' of undefined

  - gatsby-node.js:26 Object.exports.createPages
    E:/learning/gatsby/gatsby-demo-store/gatsby-node.js:26:14

success createPages — 0.200 s
success createPagesStatefully — 0.112 s
success onPreExtractQueries — 0.014 s
success update schema — 0.049 s
error GraphQL Error Encountered 5 error(s):
- Unknown field 'allMoltinCategory' on type 'Query'. Source: document `SiteTitleQuery` file: `GraphQL request`

  GraphQL request (8:5)
  7:     }
  8:     allMoltinCategory {
         ^
  9:       edges {

- Unknown field 'allMoltinCategory' on type 'Query'. Source: document `IndexPageQuery` file: `GraphQL request`

  GraphQL request (3:5)
  2:   query IndexPageQuery {
  3:     categories: allMoltinCategory {
         ^
  4:       edges {

- Unknown field 'allMoltinProduct' on type 'Query'. Source: document `allProductsQuery` file: `GraphQL request`

  GraphQL request (3:5)
  2:   query allProductsQuery {
  3:     allMoltinProduct {
         ^
  4:       edges {

- Unknown field 'moltinCategory' on type 'Query'. Source: document `eLearningGatsbyGatsbyDemoStoreSrcTemplatesCategoryPageJs373371444` file: `GraphQL request`

  GraphQL request (3:5)
  2:   query($id: String!) {
  3:     category: moltinCategory(id: { eq: $id }) {
         ^
  4:       id

- Unknown field 'moltinProduct' on type 'Query'.

      file: E:/learning/gatsby/gatsby-demo-store/src/templates/ProductPage.js

success extract queries from components — 0.439 s
success run static queries — 0.001 s
error (node:5724) DeprecationWarning: Passing lineNumber and colNumber is deprecated to @babel/code-frame. Please use `codeFrameColumns`.
success run page queries — 0.029 s — 7/7 246.69 queries/second
success write out page data — 0.061 s
success write out redirect data — 0.004 s
success Build manifest and related icons — 0.163 s
success onPostBootstrap — 0.168 s

info bootstrap finished - 25.093 s

 ERROR  Failed to compile with 4 errors                                                                          17:15:00
 error  in ./src/components/Layout/Layout.js

Module Error (from ./node_modules/eslint-loader/index.js):

E:\learning\gatsby\gatsby-demo-store\src\components\Layout\Layout.js
  33:5  error  Cannot query field "allMoltinCategory" on type "Query"  graphql/template-strings

✖ 1 problem (1 error, 0 warnings)

 @ ./src/components/Layout/index.js 1:0-35 1:0-35
 @ ./gatsby-browser.js
 @ ./.cache/api-runner-browser-plugins.js
 @ ./.cache/api-runner-browser.js
 @ ./.cache/app.js
 @ multi event-source-polyfill (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false E://learning//gatsby//gatsby-demo-store//.cache//app

 error  in ./src/pages/index.js

Module Error (from ./node_modules/eslint-loader/index.js):

E:\learning\gatsby\gatsby-demo-store\src\pages\index.js
  51:5  error  Cannot query field "allMoltinCategory" on type "Query"  graphql/template-strings

✖ 1 problem (1 error, 0 warnings)

 @ ./.cache/sync-requires.js 19:54-126
 @ ./.cache/app.js
 @ multi event-source-polyfill (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false E://learning//gatsby//gatsby-demo-store//.cache//app

 error  in ./src/pages/products.js

Module Error (from ./node_modules/eslint-loader/index.js):

E:\learning\gatsby\gatsby-demo-store\src\pages\products.js
  20:5  error  Cannot query field "allMoltinProduct" on type "Query"  graphql/template-strings

✖ 1 problem (1 error, 0 warnings)

 @ ./.cache/sync-requires.js 20:57-132
 @ ./.cache/app.js
 @ multi event-source-polyfill (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false E://learning//gatsby//gatsby-demo-store//.cache//app

 error  in ./src/styles/main.css

Module build failed (from ./node_modules/gatsby-plugin-postcss/node_modules/postcss-loader/src/index.js):
Error: Cannot find module 'tailwindcss/plugins/container'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (E:\learning\gatsby\gatsby-demo-store\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (E:\learning\gatsby\gatsby-demo-store\tailwind.config.js:356:5)
    at Module._compile (E:\learning\gatsby\gatsby-demo-store\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (E:\learning\gatsby\gatsby-demo-store\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at E:\learning\gatsby\gatsby-demo-store\node_modules\tailwindcss\lib\index.js:54:83
    at E:\learning\gatsby\gatsby-demo-store\node_modules\tailwindcss\lib\processTailwindFeatures.js:32:20
    at LazyResult.run (E:\learning\gatsby\gatsby-demo-store\node_modules\postcss\lib\lazy-result.js:295:14)
    at LazyResult.asyncTick (E:\learning\gatsby\gatsby-demo-store\node_modules\postcss\lib\lazy-result.js:208:26)

 @ ./src/styles/main.css 2:14-196 21:1-42:3 22:19-201
 @ ./src/components/Layout/Layout.js
 @ ./src/components/Layout/index.js
 @ ./gatsby-browser.js
 @ ./.cache/api-runner-browser-plugins.js
 @ ./.cache/api-runner-browser.js
 @ ./.cache/app.js
 @ multi event-source-polyfill (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false E://learning//gatsby//gatsby-demo-store//.cache//app

error × ｢wdm｣:
ERROR in ./src/components/Layout/Layout.js
Module Error (from ./node_modules/eslint-loader/index.js):

E:\learning\gatsby\gatsby-demo-store\src\components\Layout\Layout.js
  33:5  error  Cannot query field "allMoltinCategory" on type "Query"  graphql/template-strings

✖ 1 problem (1 error, 0 warnings)

 @ ./src/components/Layout/index.js 1:0-35 1:0-35
 @ ./gatsby-browser.js
 @ ./.cache/api-runner-browser-plugins.js
 @ ./.cache/api-runner-browser.js
 @ ./.cache/app.js
 @ multi event-source-polyfill (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false E://learning//gatsby//gatsby-demo-store//.cache//app

ERROR in ./src/pages/index.js
Module Error (from ./node_modules/eslint-loader/index.js):

E:\learning\gatsby\gatsby-demo-store\src\pages\index.js
  51:5  error  Cannot query field "allMoltinCategory" on type "Query"  graphql/template-strings

✖ 1 problem (1 error, 0 warnings)

 @ ./.cache/sync-requires.js 19:54-126
 @ ./.cache/app.js
 @ multi event-source-polyfill (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false E://learning//gatsby//gatsby-demo-store//.cache//app

ERROR in ./src/pages/products.js
Module Error (from ./node_modules/eslint-loader/index.js):

E:\learning\gatsby\gatsby-demo-store\src\pages\products.js
  20:5  error  Cannot query field "allMoltinProduct" on type "Query"  graphql/template-strings

✖ 1 problem (1 error, 0 warnings)

 @ ./.cache/sync-requires.js 20:57-132
 @ ./.cache/app.js
 @ multi event-source-polyfill (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false E://learning//gatsby//gatsby-demo-store//.cache//app

ERROR in ./src/styles/main.css (./node_modules/css-loader??ref--12-oneOf-1-1!./node_modules/gatsby-plugin-postcss/node_modules/postcss-loader/src??ref--12-oneOf-1-2!./src/styles/main.css)
Module build failed (from ./node_modules/gatsby-plugin-postcss/node_modules/postcss-loader/src/index.js):
Error: Cannot find module 'tailwindcss/plugins/container'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (E:\learning\gatsby\gatsby-demo-store\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (E:\learning\gatsby\gatsby-demo-store\tailwind.config.js:356:5)
    at Module._compile (E:\learning\gatsby\gatsby-demo-store\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (E:\learning\gatsby\gatsby-demo-store\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at E:\learning\gatsby\gatsby-demo-store\node_modules\tailwindcss\lib\index.js:54:83
    at E:\learning\gatsby\gatsby-demo-store\node_modules\tailwindcss\lib\processTailwindFeatures.js:32:20
    at LazyResult.run (E:\learning\gatsby\gatsby-demo-store\node_modules\postcss\lib\lazy-result.js:295:14)
    at LazyResult.asyncTick (E:\learning\gatsby\gatsby-demo-store\node_modules\postcss\lib\lazy-result.js:208:26)
 @ ./src/styles/main.css 2:14-196 21:1-42:3 22:19-201
 @ ./src/components/Layout/Layout.js
 @ ./src/components/Layout/index.js
 @ ./gatsby-browser.js
 @ ./.cache/api-runner-browser-plugins.js
 @ ./.cache/api-runner-browser.js
 @ ./.cache/app.js
 @ multi event-source-polyfill (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false E://learning//gatsby//gatsby-demo-store//.cache//app
info i ｢wdm｣: Failed to compile.
>

**Comment by cn2amz** [comment]
E:\learning\gatsby\gatsby-demo-store (master -> origin)
$ npm -v
6.4.1

E:\learning\gatsby\gatsby-demo-store (master -> origin)
$ node -v
v10.15.0

**Comment by ynnoj** [comment]
@cn2amz Looks as though you're trying to build the project without proving your Moltin store `client_id`.

> warning The @moltin/gatsby-source-moltin plugin has generated no Gatsby nodes. Do you need it?

You need to provide a Moltin `client_id` value when configuring `gatsby-source-moltin` in `gatsby-config.js` via an environment variable.

https://github.com/moltin/gatsby-demo-store/blob/6d497d10a27f0ce60f5502a20a5e9f6083d03084/gatsby-config.js#L37

Hope this helps!

**Comment by notrab** [comment]
Hi @cn2amz 

Does the above help? Feel free to respond if not and we'll help you debug it further.

**Comment by imnex** [comment]
I have the same problem. Even if I add the client id in .env file or in gatsby-config.js directly doesn't work and give the same errors like @cn2amz . Can anyone help?

**Comment by hella453** [comment]
I also have the same issue. 

```error GraphQL Error There was an error while compiling your site's GraphQL queries.
  Error: RelayParser: Encountered 5 error(s):
- Unknown field 'allMoltinCategory' on type 'Query'. Source: document `SiteTitleQuery` file: `GraphQL request`
  
  GraphQL request (8:5)
  7:     }
  8:     allMoltinCategory {
         ^
  9:       edges {
  
- Unknown field 'on_sale' on type 'MoltinProduct'. Source: document `allProductsQuery` file: `GraphQL request`
  
  GraphQL request (23:11)
  22:           }
  23:           on_sale
                ^
  24:           # main_image_alt_text
  
- Unknown field 'allMoltinCategory' on type 'Query'. Source: document `IndexPageQuery` file: `GraphQL request`
  
  GraphQL request (3:5)
  2:   query IndexPageQuery {
  3:     categories: allMoltinCategory {
         ^
  4:       edges {
  
- Unknown field 'meta_title' on type 'MoltinProduct'. Source: document `userstestDownloadsGatsbyDemoStoreMasterSrcTemplatesProductPageJs1878776835` file: `GraphQL request`
  
  GraphQL request (24:7)
  23:       }
  24:       meta_title
            ^
  25:       meta_description
  
- Unknown field 'moltinCategory' on type 'Query'. Source: document `userstestDownloadsGatsbyDemoStoreMasterSrcTemplatesCategoryPageJs373371444` file: `GraphQL request`
  
  GraphQL request (3:5)
  2:   query($id: String!) {
  3:     category: moltinCategory(id: { eq: $id }) {
         ^
  4:       id
  
    
success extract queries from components — 0.097 s
success run graphql queries — 0.012 s — 7/7 762.10 queries/second
success write out page data — 0.005 s
success write out redirect data — 0.001 s
⠂ onPostBootstrapdone generating icons for manifest
success onPostBootstrap — 0.094 s

info bootstrap finished - 10.063 s

 ERROR  Failed to compile with 3 errors                                                                                                                                                                                      2:37:30 PM

 error  in ./src/components/Layout/Layout.js

Module Error (from ./node_modules/eslint-loader/index.js):

/Users/test/Downloads/gatsby-demo-store-master/src/components/Layout/Layout.js
  33:5  error  Cannot query field "allMoltinCategory" on type "Query". Did you mean "allMoltinProduct"?  graphql/template-strings

✖ 1 problem (1 error, 0 warnings)


 @ ./src/components/Layout/index.js 1:0-35 1:0-35
 @ ./gatsby-browser.js
 @ ./.cache/api-runner-browser-plugins.js
 @ ./.cache/api-runner-browser.js
 @ ./.cache/app.js
 @ multi event-source-polyfill (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false ./.cache/app

 error  in ./src/pages/index.js

Module Error (from ./node_modules/eslint-loader/index.js):

/Users/test/Downloads/gatsby-demo-store-master/src/pages/index.js
  51:5  error  Cannot query field "allMoltinCategory" on type "Query". Did you mean "allMoltinProduct"?  graphql/template-strings

✖ 1 problem (1 error, 0 warnings)


 @ ./.cache/sync-requires.js 19:54-139
 @ ./.cache/app.js
 @ multi event-source-polyfill (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false ./.cache/app

 error  in ./src/pages/products.js

Module Error (from ./node_modules/eslint-loader/index.js):

/Users/test/Downloads/gatsby-demo-store-master/src/pages/products.js
  40:11  error  Cannot query field "on_sale" on type "MoltinProduct"  graphql/template-strings

✖ 1 problem (1 error, 0 warnings)


 @ ./.cache/sync-requires.js 20:57-145
 @ ./.cache/app.js
 @ multi event-source-polyfill (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false ./.cache/app

✖ ｢wdm｣: 
ERROR in ./src/components/Layout/Layout.js
Module Error (from ./node_modules/eslint-loader/index.js):

/Users/test/Downloads/gatsby-demo-store-master/src/components/Layout/Layout.js
  33:5  error  Cannot query field "allMoltinCategory" on type "Query". Did you mean "allMoltinProduct"?  graphql/template-strings

✖ 1 problem (1 error, 0 warnings)

 @ ./src/components/Layout/index.js 1:0-35 1:0-35
 @ ./gatsby-browser.js
 @ ./.cache/api-runner-browser-plugins.js
 @ ./.cache/api-runner-browser.js
 @ ./.cache/app.js
 @ multi event-source-polyfill (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false ./.cache/app

ERROR in ./src/pages/index.js
Module Error (from ./node_modules/eslint-loader/index.js):

/Users/test/Downloads/gatsby-demo-store-master/src/pages/index.js
  51:5  error  Cannot query field "allMoltinCategory" on type "Query". Did you mean "allMoltinProduct"?  graphql/template-strings

✖ 1 problem (1 error, 0 warnings)

 @ ./.cache/sync-requires.js 19:54-139
 @ ./.cache/app.js
 @ multi event-source-polyfill (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false ./.cache/app

ERROR in ./src/pages/products.js
Module Error (from ./node_modules/eslint-loader/index.js)
```
I added GATSBY_MOLTIN_CLIENT_ID to .env.  My Products are live. I have also created a category and assigned it to products. Should I do anything else?

**Comment by ynnoj** [comment]
This demo store is using a heavily configured Moltin store, with a handful of custom flow fields. Without those fields in your store/products the build will likely fail.

**Comment by hella453** [comment]
@ynnoj is there any documantation on how to properly configure Moltin store in order to make this project work?

**Comment by ynnoj** [comment]
@hella453 There is not. The purpose of this repository is purely for reference. It is not built to be forked/cloned and used in production.

We're building out tooling for Gatsby (which this site uses):

* [gatsby-source-moltin](https://github.com/moltin/gatsby-source-moltin)
* [gatsby-theme-moltin](https://github.com/moltin/gatsby-theme-moltin)

I'd recommend starting a fresh using the package(s) above.

Alternatively you're better off removing any of the custom flow fields not applicable to your store, starting in `gatsby-config.js` and all of the component/page files.

https://github.com/moltin/gatsby-demo-store/blob/e5fd909fc37dcff6b08f9b25dd93ea02cd97e56b/gatsby-config.js#L38-L50

**Comment by hella453** [comment]
Thanx for the advice

**Comment by ynnoj** [comment]
@hella453 No problem. Let me know if we can help any further.
