### ISSUE TITLE
Performance optimization

### ISSUE THREAD

**Issue by jhodges10** [moltin/gatsby-demo-store#14]
I noticed that all requests are being pre-flighted w/ an OPTIONS request and changes to the cart take about 2 seconds, of which almost all of it is spent on Network calls. 

Looks like this can avoided by switching from `application/json` to `application/x-www-form-urlencoded` if the Moltin API supports it, according to [this](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Simple_requests)

**Comment by notrab** [comment]
Hey @jhodes10

This could be resolved by using local storage to persist the auth token. At the time the Gatsby example was built it didn’t support custom storage, but see https://youtu.be/5ydCPvrWRmg how this works. 

All we’d need to do here is pass in some localStorage wrapper to persist the token on the client.

**Comment by jhodges10** [comment]
@notrab thanks for the clarification! Knowing it's that simple to fix that is great.

I have another performance idea. If you were to use the [Background Sync API](https://developers.google.com/web/tools/workbox/modules/workbox-background-sync), you could update the local state immediately upon an action and let the API requests run asynchronously with the UI updates which would give the appearance of performance even in a degraded connection environment.

**Comment by notrab** [comment]
@jhodges10 Great! Feel free to suggest any ideas via a PR should you have the time to contribute 😅
