### ISSUE TITLE
Demo Store

### ISSUE THREAD

**Issue by richardkeller411** [moltin/gatsby-demo-store#9]
How does moltin populate 

"meta_title
      meta_description
      on_sale
      bulb
      bulb_qty
      material
      finish
      max_watt"
In the  ProductPage.js template?

Also can we open a read only or have a sample data set to match for development.   Running Project creates errors trying to attached to different moltinID

**Comment by notrab** [comment]
Hi @richardkeller411 

Thanks for the email and issue. This project is heavily WIP and those fields above are currently required as flows on the product resource.

I will be pushing some updates next week that do not depend on on these 👍 

Until then, feel free to remove anywhere the app is requesting these 😄

**Comment by toklok** [comment]
yeah, it's definitely a WIP!  I had to remove a bunch of things that didn't make sense whatsoever.  

It's a little bit of a black box ATM, I'd like to see how everything was handled in the Dashboard in Moltin.
