### ISSUE TITLE
Algolia API

### ISSUE THREAD

**Issue by marquez138** [moltin/gatsby-demo-store#93]
Hi i am having a difficult time finding the following:
GATSBY_ALGOLIA_PLACES_APP_ID=
GATSBY_ALGOLIA_PLACES_API_KEY=
GATSBY_ALGOLIA_API_KEY=
GATSBY_ALGOLIA_APP_ID=

Looking at the angolia dashboard i only see the app id etc

Any Help would be appreciated Thanks

**Comment by notrab** [comment]
Hi @marquez138 

As per the README, you will need to create your own Algolia accounts and obtain the keys from them to enable this functionality.

> ⚠️ You will need to create an account with Algolia for search and Algolia places. Algolia is used to power the search page and Algolia places is used during the checkout process for quick address lookup.

Thanks :)
